// popularDestinations.js

export const popularDestinations = [
    { iataCode: 'SCL', name: 'Santiago de Chile - Arturo Merino Benítez' },
    { iataCode: 'ANF', name: 'Antofagasta - Andrés Sabella' },
    { iataCode: 'ARI', name: 'Arica - Chacalluta' },
    { iataCode: 'CJC', name: 'Calama - El Loa' },
    { iataCode: 'CCP', name: 'Concepción - Carriel Sur' },
    { iataCode: 'IQQ', name: 'Iquique - Diego Aracena' },
    { iataCode: 'LSC', name: 'La Serena - La Florida' },
    { iataCode: 'PMC', name: 'Puerto Montt - El Tepual' },
    { iataCode: 'PUQ', name: 'Punta Arenas - Presidente Carlos Ibáñez del Campo' },
    { iataCode: 'ZAL', name: 'Valdivia - Pichoy' },
    { iataCode: 'ZCO', name: 'Temuco - La Araucanía' },
    { iataCode: 'CPO', name: 'Copiapó - Desierto de Atacama' },
    { iataCode: 'LSQ', name: 'Los Ángeles - María Dolores' },
    { iataCode: 'ESR', name: 'El Salvador - Ricardo García Posada' },
    { iataCode: 'WPR', name: 'Porvenir - Capitán Fuentes Martínez' },
    { iataCode: 'GXQ', name: 'Coyhaique - Teniente Vidal' },
    { iataCode: 'BBA', name: 'Balmaceda - Balmaceda' },
    { iataCode: 'ZOS', name: 'Osorno - Cañal Bajo Carlos Hott Siebert' },
    { iataCode: 'MHC', name: 'Castro - Mocopulli' },
    { iataCode: 'VAP', name: 'Valparaíso - Torquemada' },
    { iataCode: 'LIM', name: 'Lima - Jorge Chávez' },
  { iataCode: 'CUZ', name: 'Cusco - Alejandro Velasco Astete' },
  { iataCode: 'AQP', name: 'Arequipa - Rodríguez Ballón' },
  { iataCode: 'TRU', name: 'Trujillo - Capitán FAP Carlos Martínez de Pinillos' },
  { iataCode: 'IQT', name: 'Iquitos - Coronel FAP Francisco Secada Vignetta' },
  { iataCode: 'JUL', name: 'Juliaca - Inca Manco Cápac' },
  { iataCode: 'PIU', name: 'Piura - Capitán FAP Guillermo Concha Iberico' },
  { iataCode: 'CIX', name: 'Chiclayo - Capitán FAP José A. Quiñones Gonzales' },
  { iataCode: 'TPP', name: 'Tarapoto - Cadete FAP Guillermo del Castillo Paredes' },
  { iataCode: 'TBP', name: 'Tumbes - Capitán FAP Pedro Canga Rodríguez' },
  { iataCode: 'PCL', name: 'Pucallpa - Capitán FAP David Abensur Rengifo' },
  { iataCode: 'TCQ', name: 'Tacna - Coronel FAP Carlos Ciriani Santa Rosa' },
  { iataCode: 'TYL', name: 'Talara - Capitán FAP Víctor Montes Arias' },
  { iataCode: 'CHM', name: 'Chimbote - Teniente FAP Jaime Montreuil Morales' },
  { iataCode: 'HUU', name: 'Huanuco - Alférez FAP David Figueroa Fernandini' },
  { iataCode: 'MGC', name: 'Moyobamba - Juan Simons Vela' },
  { iataCode: 'SMG', name: 'Saposoa - San Martin' },
  { iataCode: 'AYP', name: 'Ayacucho - Coronel FAP Alfredo Mendivil Duarte' },
  { iataCode: 'ANS', name: 'Andahuaylas - Andahuaylas' },
  { iataCode: 'ATA', name: 'Anta - Comandante FAP Germán Arias Graziani' },
  { iataCode: 'JAU', name: 'Jauja - Francisco Carlé' },
  { iataCode: 'YMS', name: 'Yurimaguas - Moisés Benzaquen Rengifo' },
  { iataCode: 'MEX', name: 'Ciudad de México - Benito Juárez' },
  { iataCode: 'CUN', name: 'Cancún' },
  { iataCode: 'GDL', name: 'Guadalajara - Miguel Hidalgo y Costilla' },
  { iataCode: 'MTY', name: 'Monterrey - General Mariano Escobedo' },
  { iataCode: 'TIJ', name: 'Tijuana - General Abelardo L. Rodríguez' },
  { iataCode: 'PVR', name: 'Puerto Vallarta - Licenciado Gustavo Díaz Ordaz' },
  { iataCode: 'SJD', name: 'San José del Cabo - Los Cabos' },
  { iataCode: 'BJX', name: 'León/Guanajuato - Del Bajío' },
  { iataCode: 'QRO', name: 'Querétaro - Intercontinental' },
  { iataCode: 'MID', name: 'Merida - Manuel Crescencio Rejón' },
  { iataCode: 'CZM', name: 'Cozumel' },
  { iataCode: 'HMO', name: 'Hermosillo - General Ignacio Pesqueira García' },
  { iataCode: 'CUL', name: 'Culiacán - Bachigualato' },
  { iataCode: 'SLP', name: 'San Luis Potosí - Ponciano Arriaga' },
  { iataCode: 'VSA', name: 'Villahermosa - Carlos Rovirosa Pérez' },
  { iataCode: 'CUU', name: 'Chihuahua - General Roberto Fierro Villalobos' },
  { iataCode: 'MXL', name: 'Mexicali - General Rodolfo Sánchez Taboada' },
  { iataCode: 'OAX', name: 'Oaxaca - Xoxocotlán' },
  { iataCode: 'VER', name: 'Veracruz - General Heriberto Jara' },
  { iataCode: 'TAM', name: 'Tampico - General Francisco Javier Mina' },
  { iataCode: 'REX', name: 'Reynosa - General Lucio Blanco' },
  { iataCode: 'TLC', name: 'Toluca - Licenciado Adolfo López Mateos' },
  { iataCode: 'ZIH', name: 'Ixtapa/Zihuatanejo' },
  { iataCode: 'LAP', name: 'La Paz - Manuel Márquez de León' },
  { iataCode: 'ZCL', name: 'Zacatecas - General Leobardo C. Ruiz' },
  { iataCode: 'AGU', name: 'Aguascalientes - Licenciado Jesús Terán Peredo' },
  { iataCode: 'TRC', name: 'Torreón - Francisco Sarabia' },
  { iataCode: 'MTT', name: 'Minatitlán - Coatzacoalcos' },
  { iataCode: 'PAZ', name: 'Poza Rica - El Tajín' },
  { iataCode: 'LMM', name: 'Los Mochis - Valle del Fuerte' },
  { iataCode: 'ZLO', name: 'Manzanillo - Playa de Oro' },
  { iataCode: 'UPN', name: 'Uruapan - General Ignacio López Rayón' },
  { iataCode: 'TPQ', name: 'Tepic - Amado Nervo' },
  { iataCode: 'TPQ', name: 'Tapachula - International' },
  { iataCode: 'TAP', name: 'Tuxtla Gutiérrez - Ángel Albino Corzo' },
  { iataCode: 'MAM', name: 'Matamoros - General Servando Canales' },
  { iataCode: 'ATL', name: 'Atlanta - Hartsfield-Jackson' },
  { iataCode: 'LAX', name: 'Los Ángeles - Los Angeles International' },
  { iataCode: 'ORD', name: 'Chicago - OHare International' },
  { iataCode: 'DFW', name: 'Dallas/Fort Worth - Dallas/Fort Worth International' },
  { iataCode: 'DEN', name: 'Denver - Denver International' },
  { iataCode: 'JFK', name: 'Nueva York - John F. Kennedy International' },
  { iataCode: 'SFO', name: 'San Francisco - San Francisco International' },
  { iataCode: 'LAS', name: 'Las Vegas - McCarran International' },
  { iataCode: 'SEA', name: 'Seattle - Seattle-Tacoma International' },
  { iataCode: 'MIA', name: 'Miami - Miami International' },
  { iataCode: 'PHX', name: 'Phoenix - Phoenix Sky Harbor International' },
  { iataCode: 'IAH', name: 'Houston - George Bush Intercontinental' },
  { iataCode: 'MCO', name: 'Orlando - Orlando International' },
  { iataCode: 'EWR', name: 'Nueva York - Newark Liberty International' },
  { iataCode: 'CLT', name: 'Charlotte - Charlotte Douglas International' },
  { iataCode: 'MSP', name: 'Minneapolis - Minneapolis-Saint Paul International' },
  { iataCode: 'DTW', name: 'Detroit - Detroit Metropolitan Wayne County' },
  { iataCode: 'PHL', name: 'Filadelfia - Philadelphia International' },
  { iataCode: 'BOS', name: 'Boston - Logan International' },
  { iataCode: 'LGA', name: 'Nueva York - LaGuardia' },
  { iataCode: 'BWI', name: 'Baltimore - Baltimore/Washington International Thurgood Marshall' },
  { iataCode: 'SLC', name: 'Salt Lake City - Salt Lake City International' },
  { iataCode: 'IAD', name: 'Washington D.C. - Washington Dulles International' },
  { iataCode: 'SAN', name: 'San Diego - San Diego International' },
  { iataCode: 'TPA', name: 'Tampa - Tampa International' },
  { iataCode: 'PDX', name: 'Portland - Portland International' },
  { iataCode: 'HNL', name: 'Honolulu - Daniel K. Inouye International' },
  { iataCode: 'DAL', name: 'Dallas - Dallas Love Field' },
  { iataCode: 'MDW', name: 'Chicago - Midway International' },
  { iataCode: 'DCA', name: 'Washington D.C. - Ronald Reagan Washington National' },
  { iataCode: 'STL', name: 'St. Louis - St. Louis Lambert International' },
  { iataCode: 'RDU', name: 'Raleigh/Durham - Raleigh-Durham International' },
  { iataCode: 'HOU', name: 'Houston - William P. Hobby' },
  { iataCode: 'BNA', name: 'Nashville - Nashville International' },
  { iataCode: 'AUS', name: 'Austin - Austin-Bergstrom International' },
  { iataCode: 'MCI', name: 'Kansas City - Kansas City International' },
  { iataCode: 'CLE', name: 'Cleveland - Cleveland Hopkins International' },
  { iataCode: 'SMF', name: 'Sacramento - Sacramento International' },
  { iataCode: 'SAT', name: 'San Antonio - San Antonio International' },
  { iataCode: 'PIT', name: 'Pittsburgh - Pittsburgh International' },
  { iataCode: 'SJC', name: 'San José - Norman Y. Mineta San Jose International' },
  { iataCode: 'CVG', name: 'Cincinnati - Cincinnati/Northern Kentucky International' },
  { iataCode: 'IND', name: 'Indianápolis - Indianapolis International' },
  { iataCode: 'MKE', name: 'Milwaukee - General Mitchell International' },
  { iataCode: 'SNA', name: 'Santa Ana - John Wayne' },
  { iataCode: 'JAX', name: 'Jacksonville - Jacksonville International' },
  { iataCode: 'OGG', name: 'Kahului - Kahului' },
  { iataCode: 'ABQ', name: 'Albuquerque - Albuquerque International Sunport' },
  { iataCode: 'OMA', name: 'Omaha - Eppley Airfield' },
  { iataCode: 'ANC', name: 'Anchorage - Ted Stevens Anchorage International' },
  { iataCode: 'RNO', name: 'Reno - Reno-Tahoe International' },
  { iataCode: 'BUF', name: 'Búfalo - Buffalo Niagara International' },
  { iataCode: 'ONT', name: 'Ontario - Ontario International' },
  { iataCode: 'LIH', name: 'Lihue - Lihue' },
  { iataCode: 'RIC', name: 'Richmond - Richmond International' },
  { iataCode: 'CHS', name: 'Charleston - Charleston International' },
  { iataCode: 'BOI', name: 'Boise - Boise Air Terminal' },
  { iataCode: 'BOI', name: 'Spokane - Spokane International' },
  { iataCode: 'GEG', name: 'Spokane - Spokane International' },
    { iataCode: 'BUE', name: 'Buenos Aires' },
    { iataCode: 'GRU', name: 'Sao Paulo - Guarulhos' },
  { iataCode: 'GIG', name: 'Rio de Janeiro - Galeão' },
  { iataCode: 'CGH', name: 'Sao Paulo - Congonhas' },
  { iataCode: 'SDU', name: 'Río de Janeiro - Santos Dumont' },
  { iataCode: 'BSB', name: 'Brasilia' },
  { iataCode: 'CNF', name: 'Belo Horizonte - Confins' },
  { iataCode: 'POA', name: 'Porto Alegre - Salgado Filho' },
  { iataCode: 'SSA', name: 'Salvador - Deputado Luís Eduardo Magalhães' },
  { iataCode: 'CWB', name: 'Curitiba - Afonso Pena' },
  { iataCode: 'REC', name: 'Recife - Guararapes' },
  { iataCode: 'FOR', name: 'Fortaleza - Pinto Martins' },
  { iataCode: 'VCP', name: 'Campinas - Viracopos' },
  { iataCode: 'BEL', name: 'Belem - Val de Cans' },
  { iataCode: 'MAO', name: 'Manaus - Eduardo Gomes' },
  { iataCode: 'NAT', name: 'Natal - Governador Aluízio Alves' },
  { iataCode: 'CGB', name: 'Cuiabá - Marechal Rondon' },
  { iataCode: 'MCZ', name: 'Maceió - Zumbi dos Palmares' },
  { iataCode: 'VIX', name: 'Vitória - Eurico de Aguiar Salles' },
  { iataCode: 'GYN', name: 'Goiânia - Santa Genoveva' },
  { iataCode: 'SLZ', name: 'Sao Luís - Marechal Cunha Machado' },
  { iataCode: 'JOI', name: 'Joinville - Lauro Carneiro de Loyola' },
  { iataCode: 'NVT', name: 'Navegantes - Ministro Victor Konder' },
  { iataCode: 'FLN', name: 'Florianópolis - Hercílio Luz' },
  { iataCode: 'IGU', name: 'Foz do Iguaçu - Cataratas' },
  { iataCode: 'AJU', name: 'Aracaju - Santa Maria' },
  { iataCode: 'THE', name: 'Teresina - Senador Petrônio Portella' },
  { iataCode: 'BPS', name: 'Porto Seguro' },
  { iataCode: 'PVH', name: 'Porto Velho - Governador Jorge Teixeira de Oliveira' },
  { iataCode: 'RBR', name: 'Rio Branco - Plácido de Castro' },
  { iataCode: 'TFF', name: 'Tefé' },
  { iataCode: 'JDO', name: 'Juazeiro do Norte - Orlando Bezerra de Menezes' },
  { iataCode: 'STM', name: 'Santarém - Maestro Wilson Fonseca' },
  { iataCode: 'CPV', name: 'Campina Grande - Presidente João Suassuna' },
  { iataCode: 'CZS', name: 'Cruzeiro do Sul' },
  { iataCode: 'ATM', name: 'Altamira' },
  { iataCode: 'PPB', name: 'Presidente Prudente - Adhemar de Barros' },
  { iataCode: 'MII', name: 'Marília - Frank Miloye Milenkowichi' },
  { iataCode: 'CAW', name: 'Campos dos Goytacazes - Bartolomeu Lysandro' },
  { iataCode: 'IZA', name: 'Juiz de Fora - Zona da Mata' },
  { iataCode: 'UDI', name: 'Uberlândia - Tenente Coronel Aviador César Bombonato' },
  { iataCode: 'UBA', name: 'Uberaba - Mário de Almeida Franco' },
    { iataCode: 'BOG', name: 'Bogotá - El Dorado' },
    { iataCode: 'MDE', name: 'Medellín - José María Córdova' },
    { iataCode: 'CLO', name: 'Cali - Alfonso Bonilla Aragón' },
    { iataCode: 'CTG', name: 'Cartagena - Rafael Núñez' },
    { iataCode: 'BAQ', name: 'Barranquilla - Ernesto Cortissoz' },
    { iataCode: 'SMR', name: 'Santa Marta - Simón Bolívar' },
    { iataCode: 'ADZ', name: 'San Andrés - Gustavo Rojas Pinilla' },
    { iataCode: 'PEI', name: 'Pereira - Matecaña' },
    { iataCode: 'AXM', name: 'Armenia - El Edén' },
    { iataCode: 'BGA', name: 'Bucaramanga - Palonegro' },
    { iataCode: 'CUC', name: 'Cucuta - Camilo Daza' },
    { iataCode: 'LET', name: 'Leticia - Alfredo Vásquez Cobo' },
    { iataCode: 'MZL', name: 'Manizales - La Nubia' },
    { iataCode: 'EOH', name: 'Medellín - Olaya Herrera' },
    { iataCode: 'NVA', name: 'Neiva - Benito Salas' },
    { iataCode: 'PPN', name: 'Popayán - Guillermo León Valencia' },
    { iataCode: 'PSO', name: 'Pasto - Antonio Nariño' },
    { iataCode: 'RCH', name: 'Riohacha - Almirante Padilla' },
    { iataCode: 'TME', name: 'Tame - Gabriel Vargas Santos' },
    { iataCode: 'VUP', name: 'Valledupar - Alfonso López Pumarejo' },
    { iataCode: 'VVC', name: 'Villavicencio - Vanguardia' },
    { iataCode: 'CIM', name: 'Cimitarra - Cimitarra' },
    { iataCode: 'BUN', name: 'Buenaventura - Gerardo Tobar López' },
    { iataCode: 'TCO', name: 'Tumaco - La Florida' },
    { iataCode: 'MCJ', name: 'Maicao - Jorge Isaacs' },
    { iataCode: 'LPD', name: 'La Pedrera - La Pedrera' },
    { iataCode: 'PDA', name: 'Puerto Inírida - Obando' },
    { iataCode: 'MVP', name: 'Mitú - Fabio Alberto León Bentley' },
    { iataCode: 'EJA', name: 'Barrancabermeja - Yariguíes' },
    { iataCode: 'CVE', name: 'Covenas - Covenas' },
    { iataCode: 'GPI', name: 'Guapi - Juan Casiano' },
    { iataCode: 'GRU', name: 'São Paulo' },
    { iataCode: 'EZE', name: 'Buenos Aires - Ministro Pistarini (Ezeiza)' },
    { iataCode: 'AEP', name: 'Buenos Aires - Aeroparque Jorge Newbery' },
    { iataCode: 'COR', name: 'Cordoba - Ingeniero Ambrosio Taravella' },
    { iataCode: 'MDZ', name: 'Mendoza - El Plumerillo' },
    { iataCode: 'ROS', name: 'Rosario - Islas Malvinas' },
    { iataCode: 'BRC', name: 'San Carlos de Bariloche - Teniente Luis Candelaria' },
    { iataCode: 'NQN', name: 'Neuquén - Presidente Perón' },
    { iataCode: 'SLA', name: 'Salta - Martín Miguel de Güemes' },
    { iataCode: 'TUC', name: 'San Miguel de Tucumán - Teniente General Benjamín Matienzo' },
    { iataCode: 'IGR', name: 'Puerto Iguazú - Cataratas del Iguazú' },
    { iataCode: 'USH', name: 'Ushuaia - Malvinas Argentinas' },
    { iataCode: 'REL', name: 'Trelew - Almirante Marco Andrés Zar' },
    { iataCode: 'RGL', name: 'Rio Gallegos - Piloto Civil Norberto Fernández' },
    { iataCode: 'FTE', name: 'El Calafate - Comandante Armando Tola' },
    { iataCode: 'JUJ', name: 'San Salvador de Jujuy - Gobernador Horacio Guzmán' },
    { iataCode: 'AFA', name: 'San Rafael - Suboficial Ayudante Santiago Germano' },
    { iataCode: 'CRD', name: 'Comodoro Rivadavia - General Enrique Mosconi' },
    { iataCode: 'VDM', name: 'Viedma - Gobernador Edgardo Castello' },
    { iataCode: 'RHD', name: 'Termas de Río Hondo' },
    { iataCode: 'BHI', name: 'Bahía Blanca - Comandante Espora' },
    { iataCode: 'PMY', name: 'Puerto Madryn - El Tehuelche' },
    { iataCode: 'RSA', name: 'Santa Rosa - Santa Rosa' },
    { iataCode: 'LGS', name: 'Malargüe - Comodoro D. Ricardo Salomón' },
    { iataCode: 'CPC', name: 'San Martín de los Andes - Aviador Carlos Campos' },
    { iataCode: 'VLG', name: 'Villa Gesell - Villa Gesell' },
    { iataCode: 'EHL', name: 'El Bolsón - El Bolsón' },
    { iataCode: 'RCU', name: 'Rio Cuarto - Las Higueras' },
    { iataCode: 'PSS', name: 'Posadas - Libertador General José de San Martín' },
    { iataCode: 'CNQ', name: 'Corrientes - Doctor Fernando Piragine Niveyro' },
    { iataCode: 'RES', name: 'Resistencia - Resistencia' },
    { iataCode: 'FMA', name: 'Formosa - El Pucú' },
    { iataCode: 'CLX', name: 'Clorinda' },
    { iataCode: 'OYA', name: 'Goya' },
    { iataCode: 'LLS', name: 'Las Lomitas' },
    { iataCode: 'SDE', name: 'Santiago del Estero - Vicecomodoro Ángel de la Paz Aragonés' },
    { iataCode: 'IRJ', name: 'La Rioja - Capitán Vicente Almandos Almonacid' },
    { iataCode: 'CTC', name: 'Catamarca - Coronel Felipe Varela' },
    { iataCode: 'VDR', name: 'Villa Dolores' },
    { iataCode: 'LUQ', name: 'San Luis - Brigadier Mayor César Raúl Ojeda' },
    { iataCode: 'CNQ', name: 'Corrientes - Dr. Fernando Piragine Niveyro' },
    { iataCode: 'RGA', name: 'Rio Grande - Hermes Quijada' },
    { iataCode: 'LHR', name: 'Londres - Heathrow' },
    { iataCode: 'FRA', name: 'Frankfurt - Frankfurt am Main' },
    { iataCode: 'AMS', name: 'Amsterdam - Schiphol' },
    { iataCode: 'MAD', name: 'Madrid - Adolfo Suárez Madrid-Barajas' },
    { iataCode: 'BCN', name: 'Barcelona - El Prat' },
    { iataCode: 'MUC', name: 'Múnich - Franz Josef Strauß' },
    { iataCode: 'FCO', name: 'Roma - Leonardo da Vinci-Fiumicino' },
    { iataCode: 'LGW', name: 'Londres - Gatwick' },
    { iataCode: 'ZRH', name: 'Zúrich - Zúrich' },
    { iataCode: 'CPH', name: 'Copenhague - Kastrup' },
    { iataCode: 'OSL', name: 'Oslo - Gardermoen' },
    { iataCode: 'ARN', name: 'Estocolmo - Arlanda' },
    { iataCode: 'HEL', name: 'Helsinki - Vantaa' },
    { iataCode: 'DUB', name: 'Dublín - Dublín' },
    { iataCode: 'BRU', name: 'Bruselas - Bruselas' },
    { iataCode: 'VIE', name: 'Viena - Schwechat' },
    { iataCode: 'PRG', name: 'Praga - Václav Havel' },
    { iataCode: 'WAW', name: 'Varsovia - Frederic Chopin' },
    { iataCode: 'BUD', name: 'Budapest - Ferenc Liszt' },
    { iataCode: 'ATH', name: 'Atenas - Eleftherios Venizelos' },
    { iataCode: 'LIS', name: 'Lisboa - Humberto Delgado' },
    { iataCode: 'MAN', name: 'Mánchester - Mánchester' },
    { iataCode: 'DUS', name: 'Düsseldorf - Düsseldorf' },
    { iataCode: 'HAM', name: 'Hamburgo - Helmut Schmidt' },
    { iataCode: 'BER', name: 'Berlín - Brandenburg' },
    { iataCode: 'GVA', name: 'Ginebra - Ginebra' },
    { iataCode: 'MXP', name: 'Milán - Malpensa' },
    { iataCode: 'LIN', name: 'Milán - Linate' },
    { iataCode: 'VCE', name: 'Venecia - Marco Polo' },
    { iataCode: 'NAP', name: 'Napoles - Capodichino' },
    { iataCode: 'PMI', name: 'Palma de Mallorca - Palma de Mallorca' },
    { iataCode: 'NCE', name: 'Niza - Costa Azul' },
    { iataCode: 'LYS', name: 'Lyon - Saint Exupéry' },
    { iataCode: 'TLL', name: 'Tallin - Lennart Meri' },
    { iataCode: 'RIX', name: 'Riga - Riga' },
    { iataCode: 'VNO', name: 'Vilna - Vilnius' },
    { iataCode: 'LED', name: 'San Petersburgo - Pulkovo' },
    { iataCode: 'SVO', name: 'Moscú - Sheremetyevo' },
    { iataCode: 'DME', name: 'Moscú - Domodedovo' },
    { iataCode: 'IST', name: 'Estambul - Istanbul' },
    { iataCode: 'SAW', name: 'Estambul - Sabiha Gökçen' },
    { iataCode: 'OTP', name: 'Bucarest - Henri Coandă' },
    { iataCode: 'SOF', name: 'Sofía - Sofía' },
    { iataCode: 'BEG', name: 'Belgrado - Nikola Tesla' },
    { iataCode: 'ZAG', name: 'Zagreb - Franjo Tuđman' },
    { iataCode: 'DBV', name: 'Dubrovnik - Dubrovnik' },
    { iataCode: 'SPU', name: 'Split - Split' },
    { iataCode: 'LCA', name: 'Larnaca - Larnaca' },
    { iataCode: 'MLA', name: 'La Valeta - Malta' },
    { iataCode: 'SKG', name: 'Salónica - Macedonia' },
    { iataCode: 'BFS', name: 'Belfast - Belfast International' },
    { iataCode: 'EMA', name: 'East Midlands - East Midlands' },
    { iataCode: 'LTN', name: 'Londres - Luton' },
    { iataCode: 'STN', name: 'Londres - Stansted' },
    { iataCode: 'EDI', name: 'Edimburgo - Edinburgh' },
    { iataCode: 'GLA', name: 'Glasgow - Glasgow International' },
    { iataCode: 'ABZ', name: 'Aberdeen - Aberdeen International' },
    { iataCode: 'BHX', name: 'Birmingham - Birmingham' },
    { iataCode: 'NCL', name: 'Newcastle - Newcastle International' },
    { iataCode: 'LBA', name: 'Leeds/Bradford - Leeds Bradford' },
    { iataCode: 'BHD', name: 'Belfast - George Best Belfast City' },
    { iataCode: 'SEN', name: 'Southend - London Southend' },
    { iataCode: 'PEK', name: 'Beijing - Capital International' },
    { iataCode: 'PVG', name: 'Shanghai - Pudong International' },
    { iataCode: 'HND', name: 'Tokyo - Haneda' },
    { iataCode: 'NRT', name: 'Tokyo - Narita' },
    { iataCode: 'ICN', name: 'Seoul - Incheon International' },
    { iataCode: 'HKG', name: 'Hong Kong - Hong Kong International' },
    { iataCode: 'SIN', name: 'Singapore - Changi' },
    { iataCode: 'BKK', name: 'Bangkok - Suvarnabhumi' },
    { iataCode: 'DEL', name: 'Delhi - Indira Gandhi International' },
    { iataCode: 'BOM', name: 'Mumbai - Chhatrapati Shivaji Maharaj International' },
    { iataCode: 'KUL', name: 'Kuala Lumpur - Kuala Lumpur International' },
    { iataCode: 'MNL', name: 'Manila - Ninoy Aquino International' },
    { iataCode: 'CGK', name: 'Jakarta - Soekarno-Hatta International' },
    { iataCode: 'CAN', name: 'Guangzhou - Baiyun International' },
    { iataCode: 'SZX', name: 'Shenzhen - Bao\'an International' },
    { iataCode: 'CTU', name: 'Chengdu - Shuangliu International' },
    { iataCode: 'KIX', name: 'Osaka - Kansai International' },
    { iataCode: 'FUK', name: 'Fukuoka - Fukuoka' },
    { iataCode: 'KHH', name: 'Kaohsiung - Kaohsiung International' },
    { iataCode: 'TPE', name: 'Taipei - Taoyuan International' },
    { iataCode: 'DPS', name: 'Denpasar - Ngurah Rai International' },
    { iataCode: 'SGN', name: 'Ho Chi Minh City - Tan Son Nhat International' },
    { iataCode: 'HAN', name: 'Hanoi - Noi Bai International' },
    { iataCode: 'CEB', name: 'Cebu - Mactan-Cebu International' },
    { iataCode: 'KTM', name: 'Kathmandu - Tribhuvan International' },
    { iataCode: 'PNH', name: 'Phnom Penh - Phnom Penh International' },
    { iataCode: 'VTE', name: 'Vientiane - Wattay International' },
    { iataCode: 'RGN', name: 'Yangon - Yangon International' },
    { iataCode: 'ULN', name: 'Ulaanbaatar - Chinggis Khaan International' },
    { iataCode: 'TAS', name: 'Tashkent - Islam Karimov Tashkent International' },
    { iataCode: 'ALA', name: 'Almaty - Almaty International' },
    { iataCode: 'NQZ', name: 'Nur-Sultan - Nursultan Nazarbayev International' },
    { iataCode: 'KHI', name: 'Karachi - Jinnah International' },
    { iataCode: 'LHE', name: 'Lahore - Allama Iqbal International' },
    { iataCode: 'ISB', name: 'Islamabad - Islamabad International' },
    { iataCode: 'IKA', name: 'Tehran - Imam Khomeini International' },
    { iataCode: 'THR', name: 'Tehran - Mehrabad International' },
    { iataCode: 'TLV', name: 'Tel Aviv - Ben Gurion' },
    { iataCode: 'RUH', name: 'Riyadh - King Khalid International' },
    { iataCode: 'JED', name: 'Jeddah - King Abdulaziz International' },
    { iataCode: 'DMM', name: 'Dammam - King Fahd International' },
    { iataCode: 'DOH', name: 'Doha - Hamad International' },
    { iataCode: 'AUH', name: 'Abu Dhabi - Abu Dhabi International' },
    { iataCode: 'DXB', name: 'Dubai - Dubai International' },
    { iataCode: 'SHJ', name: 'Sharjah - Sharjah International' },
    { iataCode: 'BAH', name: 'Bahrain - Bahrain International' },
    { iataCode: 'MCT', name: 'Muscat - Muscat International' },
    { iataCode: 'KWI', name: 'Kuwait City - Kuwait International' },
    { iataCode: 'MLE', name: 'Malé - Velana International' },
    { iataCode: 'CMB', name: 'Colombo - Bandaranaike International' },
    { iataCode: 'PTY', name: 'Panamá - Tocumen International' },
    { iataCode: 'SJO', name: 'San José - Juan Santamaría International' },
    { iataCode: 'LIR', name: 'Liberia - Daniel Oduber Quirós International' },
    { iataCode: 'SAL', name: 'San Salvador - El Salvador International' },
    { iataCode: 'TGU', name: 'Tegucigalpa - Toncontín International' },
    { iataCode: 'SAP', name: 'San Pedro Sula - Ramón Villeda Morales International' },
    { iataCode: 'RTB', name: 'Roatán - Juan Manuel Gálvez International' },
    { iataCode: 'BZE', name: 'Belice City - Philip S. W. Goldson International' },
    { iataCode: 'MGA', name: 'Managua - Augusto C. Sandino International' },
    { iataCode: 'GUA', name: 'Ciudad de Guatemala - La Aurora International' },
    { iataCode: 'CZL', name: 'Cozumel - Cozumel International' },
    { iataCode: 'HAV', name: 'La Habana - José Martí International' },
    { iataCode: 'SNU', name: 'Santa Clara - Abel Santamaría International' },
    { iataCode: 'VRA', name: 'Varadero - Juan Gualberto Gómez International' },
    { iataCode: 'GCM', name: 'Gran Caimán - Owen Roberts International' },
    { iataCode: 'KIN', name: 'Kingston - Norman Manley International' },
    { iataCode: 'MBJ', name: 'Montego Bay - Sangster International' },
    { iataCode: 'NAS', name: 'Nassau - Lynden Pindling International' },
    { iataCode: 'PLS', name: 'Providenciales - Providenciales International' },
    { iataCode: 'SXM', name: 'Sint Maarten - Princess Juliana International' },
    { iataCode: 'AUA', name: 'Aruba - Queen Beatrix International' },
    { iataCode: 'CUR', name: 'Curazao - Hato International' },
    { iataCode: 'BON', name: 'Bonaire - Flamingo International' },
    { iataCode: 'POS', name: 'Puerto España - Piarco International' },
    { iataCode: 'TAB', name: 'Tobago - A.N.R. Robinson International' },
    { iataCode: 'SJU', name: 'San Juan - Luis Muñoz Marín International' },
    { iataCode: 'STT', name: 'Saint Thomas - Cyril E. King' },
    { iataCode: 'STX', name: 'Saint Croix - Henry E. Rohlsen' },
    { iataCode: 'SDQ', name: 'Santo Domingo - Las Américas International' },
    { iataCode: 'PUJ', name: 'Punta Cana - Punta Cana International' },
    { iataCode: 'POP', name: 'Puerto Plata - Gregorio Luperón International' },
    { iataCode: 'SXM', name: 'Sint Maarten - Princess Juliana International' },
    { iataCode: 'FDF', name: 'Fort-de-France - Martinique Aimé Césaire International' },
    { iataCode: 'PTP', name: 'Pointe-à-Pitre - Pointe-à-Pitre International' },
    { iataCode: 'BDA', name: 'Bermuda - L.F. Wade International' },
    { iataCode: 'ANU', name: 'Antigua - V.C. Bird International' },
    { iataCode: 'GND', name: 'Granada - Maurice Bishop International' },
    { iataCode: 'SLU', name: 'Santa Lucía - George F. L. Charles' },
    { iataCode: 'UVF', name: 'Santa Lucía - Hewanorra International' },
    { iataCode: 'EIS', name: 'Tortola - Terrance B. Lettsome International' },
    { iataCode: 'SKB', name: 'Saint Kitts - Robert L. Bradshaw International' },
    { iataCode: 'CCS', name: 'Caracas - Simón Bolívar International' },
    { iataCode: 'MAR', name: 'Maracaibo - La Chinita International' },
    { iataCode: 'VLN', name: 'Valencia - Arturo Michelena International' },
    { iataCode: 'PMV', name: 'Porlamar - Santiago Mariño Caribbean International' },
    { iataCode: 'BLA', name: 'Barcelona - General José Antonio Anzoátegui International' },
    { iataCode: 'PZO', name: 'Puerto Ordaz - Manuel Carlos Piar Guayana' },
    { iataCode: 'LFR', name: 'La Fría - La Fría' },
    { iataCode: 'LSP', name: 'Las Piedras - Josefa Camejo International' },
    { iataCode: 'CBL', name: 'Ciudad Bolívar - Tomás de Heres' },
    { iataCode: 'CUM', name: 'Cumaná - Antonio José de Sucre' },
    { iataCode: 'CZE', name: 'Coro - José Leonardo Chirino' },
    { iataCode: 'ELX', name: 'El Tigre - El Tigre' },
    { iataCode: 'EOR', name: 'El Dorado - El Dorado' },
    { iataCode: 'GUI', name: 'Guiria - Guiria' },
    { iataCode: 'LAG', name: 'La Guaira - La Guaira' },
    { iataCode: 'LSP', name: 'Punto Fijo - Josefa Camejo International' },
    { iataCode: 'MUN', name: 'Maturín - José Tadeo Monagas International' },
    { iataCode: 'PYH', name: 'Puerto Ayacucho - Cacique Aramare' },
    { iataCode: 'SCI', name: 'San Cristóbal - Paramillo' },
    { iataCode: 'SFD', name: 'San Fernando de Apure - Las Flecheras' },
    { iataCode: 'SOM', name: 'San Tomé - San Tomé' },
    { iataCode: 'STD', name: 'Santo Domingo - Mayor Buenaventura Vivas' },
    { iataCode: 'SNV', name: 'Santa Elena de Uairén - Santa Elena de Uairén' },
    { iataCode: 'TUV', name: 'Tucupita - Tucupita' },
    { iataCode: 'VIG', name: 'El Vigía - Juan Pablo Pérez Alfonzo' },
    { iataCode: 'UIO', name: 'Quito - Mariscal Sucre International' },
    { iataCode: 'GYE', name: 'Guayaquil - José Joaquín de Olmedo International' },
    { iataCode: 'CUE', name: 'Cuenca - Mariscal La Mar' },
    { iataCode: 'GPS', name: 'Galápagos (Baltra) - Seymour' },
    { iataCode: 'SCY', name: 'Galápagos (San Cristóbal) - San Cristóbal' },
    { iataCode: 'MEC', name: 'Manta - Eloy Alfaro International' },
    { iataCode: 'LTX', name: 'Latacunga - Cotopaxi International' },
    { iataCode: 'ESM', name: 'Esmeraldas - General Rivadeneira' },
    { iataCode: 'XMS', name: 'Macas - Coronel Edmundo Carvajal' },
    { iataCode: 'MCH', name: 'Machala - General Manuel Serrano' },
    { iataCode: 'PTZ', name: 'Pastaza - Rio Amazonas' },
    { iataCode: 'TPC', name: 'Tarapoa - Tarapoa' },
    { iataCode: 'LGQ', name: 'Nueva Loja (Lago Agrio) - Lago Agrio' },
    { iataCode: 'TPN', name: 'Tiputini - Tiputini' },
    { iataCode: 'LOH', name: 'Loja - Ciudad de Catamayo' },
    { iataCode: 'PVO', name: 'Portoviejo - Reales Tamarindos' },
    { iataCode: 'TSC', name: 'Taisha - Taisha' },
    { iataCode: 'PYO', name: 'Putumayo - Putumayo' },
    { iataCode: 'MVD', name: 'Montevideo - Carrasco International' },
    { iataCode: 'PDP', name: 'Punta del Este - Capitán Corbeta CA Curbelo International' },
    { iataCode: 'STY', name: 'Salto - Nueva Hespérides International' },
    { iataCode: 'MLZ', name: 'Melo - Cerro Largo' },
    { iataCode: 'ATI', name: 'Artigas - Artigas International' },
    { iataCode: 'CYR', name: 'Colonia del Sacramento - Laguna de los Patos International' },
    { iataCode: 'DZO', name: 'Durazno - Santa Bernardina International' },
    { iataCode: 'PDU', name: 'Paysandú - Tydeo Larre Borges' },
    { iataCode: 'RVY', name: 'Rivera - Rivera International' },
    { iataCode: 'TAW', name: 'Tacuarembó - Tacuarembó' },
    { iataCode: 'TYT', name: 'Treinta y Tres - Treinta y Tres' },
    { iataCode: 'ASU', name: 'Asunción - Silvio Pettirossi International' },
    { iataCode: 'AGT', name: 'Ciudad del Este - Guaraní International' },
    { iataCode: 'PJC', name: 'Pedro Juan Caballero - Dr. Augusto Roberto Fuster International' },
    { iataCode: 'CIO', name: 'Concepción - Teniente Colina' },
    { iataCode: 'ESG', name: 'Mariscal Estigarribia - Dr. Luis María Argaña International' },
    { iataCode: 'PIL', name: 'Pilar - Carlos Miguel Jiménez' },
    { iataCode: 'AXM', name: 'Filadelfia - Filadelfia' },
    { iataCode: 'VMI', name: 'Vallemí - Vallemí' },
    { iataCode: 'PIL', name: 'Pilar - Carlos Miguel Jiménez' },
    { iataCode: 'FLM', name: 'Filadelfia - Filadelfia' },
    { iataCode: 'VVI', name: 'Santa Cruz - Viru Viru International' },
    { iataCode: 'LPB', name: 'La Paz - El Alto International' },
    { iataCode: 'CBB', name: 'Cochabamba - Jorge Wilstermann International' },
    { iataCode: 'TJA', name: 'Tarija - Capitán Oriel Lea Plaza' },
    { iataCode: 'TDD', name: 'Trinidad - Teniente Jorge Henrich Arauz' },
    { iataCode: 'RIB', name: 'Riberalta - Capitán Av. Selin Zeitun Lopez' },
    { iataCode: 'PSZ', name: 'Puerto Suárez - Capitán Av. Salvador Ogaya G.' },
    { iataCode: 'SRZ', name: 'Santa Cruz - El Trompillo' },
    { iataCode: 'UYU', name: 'Uyuni - Joya Andina' },
    { iataCode: 'RBQ', name: 'Rurrenabaque - Rurrenabaque' },
    { iataCode: 'SRE', name: 'Sucre - Alcantari International' },
    { iataCode: 'BYC', name: 'Yacuiba - Yacuiba' },
    { iataCode: 'CIJ', name: 'Cobija - Capitán Aníbal Arab Fadul' },
    { iataCode: 'GYA', name: 'Guayaramerín - Guayaramerín' },
    { iataCode: 'REY', name: 'Riberalta - Reyes' },
    { iataCode: 'CDG', name: 'Paris - Charles de Gaulle' },
    { iataCode: 'ORY', name: 'Paris - Orly' },
    { iataCode: 'BVA', name: 'Beauvais - Beauvais-Tillé' },
    { iataCode: 'MRS', name: 'Marsella - Provence' },
    { iataCode: 'NCE', name: 'Niza - Côte d\'Azur' },
    { iataCode: 'LYS', name: 'Lyon - Saint-Exupéry' },
    { iataCode: 'TLS', name: 'Toulouse - Blagnac' },
    { iataCode: 'BOD', name: 'Burdeos - Mérignac' },
    { iataCode: 'SXB', name: 'Estrasburgo - Entzheim' },
    { iataCode: 'LIL', name: 'Lille - Lesquin' },
    { iataCode: 'NTE', name: 'Nantes - Atlantique' },
    { iataCode: 'MPL', name: 'Montpellier - Méditerranée' },
    { iataCode: 'BIA', name: 'Bastia - Poretta' },
    { iataCode: 'AJA', name: 'Ajaccio - Napoleón Bonaparte' },
    { iataCode: 'FNI', name: 'Nîmes - Garons' },
    { iataCode: 'RNS', name: 'Rennes - Saint-Jacques' },
    { iataCode: 'CFR', name: 'Caen - Carpiquet' },
    { iataCode: 'BIQ', name: 'Biarritz - Pays Basque' },
    { iataCode: 'UIP', name: 'Quimper - Pluguffan' },
    { iataCode: 'LRH', name: 'La Rochelle - Île de Ré' },
    { iataCode: 'LRT', name: 'Lorient - Lann Bihoué' },
    { iataCode: 'BES', name: 'Brest - Bretagne' },
    { iataCode: 'PGF', name: 'Perpiñán - Rivesaltes' },
    { iataCode: 'PIS', name: 'Poitiers - Biard' },
    { iataCode: 'LDE', name: 'Lourdes - Tarbes-Pyrénées' },
    { iataCode: 'PUF', name: 'Pau - Pyrénées' },
    { iataCode: 'BVA', name: 'Beauvais - Tillé' },
    { iataCode: 'XCR', name: 'Châlons-en-Champagne - Vatry' },
    { iataCode: 'DOL', name: 'Deauville - Saint-Gatien' },
    { iataCode: 'MLH', name: 'Mulhouse - EuroAirport Basel-Mulhouse-Freiburg' },
    { iataCode: 'CCF', name: 'Carcasona - Salvaza' },
    { iataCode: 'TLN', name: 'Toulon - Hyères' },
    { iataCode: 'LIG', name: 'Limoges - Bellegarde' },
    { iataCode: 'PIS', name: 'Poitiers - Biard' },
    { iataCode: 'ANG', name: 'Angers - Loire' },
    { iataCode: 'ETZ', name: 'Metz-Nancy - Lorraine' },
    { iataCode: 'TUF', name: 'Tours - Val de Loire' },
    { iataCode: 'CFE', name: 'Clermont-Ferrand - Auvergne' },
    { iataCode: 'RAY', name: 'Bastia - Calvi Sainte-Catherine' },
    { iataCode: 'DNR', name: 'Dinard - Pleurtuit-Saint-Malo' },


  ];
  export function searchPopularDestinations(query) {
    return popularDestinations.filter(dest => 
      dest.name.toLowerCase().includes(query.toLowerCase()) ||
      dest.iataCode.toLowerCase().includes(query.toLowerCase())
    );
  }