const airlineNames = {
    AA: 'AmericanAirlines',
    DL: 'DeltaAirlines',
    UA: 'UnitedAirlines',
    AC: 'AirCanada',
    AF: 'AirFrance',
    BA: 'BritishAirways',
    CX: 'Cathay Pacific',
    EK: 'Emirates',
    JL: 'JapanAirlines',
    LH: 'Lufthansa',
    QF: 'Qantas',
    QR: 'QatarAirways',
    SQ: 'SingaporeAirlines',
    TG: 'Thai Airways',
    VS: 'Virgin Atlantic',
    WN: 'Southwest Airlines',
    NZ: 'Air New Zealand',
    AZ: 'Alitalia',
    AY: 'Finnair',
    BR: 'EVA Air',
    CI: 'ChinaAirlines',
    CZ: 'China Southern Airlines',
    ET: 'Ethiopian Airlines',
    EY: 'EtihadAirways',
    GA: 'Garuda Indonesia',
    IB: 'Iberia',
    KL: 'KLM',
    MH: 'Malaysia Airlines',
    MS: 'EgyptAir',
    NH: 'All Nippon Airways (ANA)',
    OS: 'Austrian Airlines',
    SK: 'SAS Scandinavian Airlines',
    SU: 'Aeroflot Russian Airlines',
    TK: 'TurkishAirlines',
    VN: 'Vietnam Airlines',
    ZH: 'Shenzhen Airlines',
    LA: 'LATAMAirlines',
    AR: 'Aerolineas',
    CM: 'CopaAirlines',
    VY: 'Vueling',
    AV: 'Avianca',
    UX: 'AirEuropa',
    AT: 'RoyalAirMaroc',
    TP: 'Flytap',
    PC: 'Flypgs',
    RO: 'Tarom',
    JU: 'AirSerbia',
    SN: 'BrusselsAirlines',
    KM: 'kmmaltairlines',
    A3: 'AegeanAir',
    JA: 'JetSmart',
    H2: 'SkyAirline',
    ZP: 'Paranair',
   
 

  };
  
  export default airlineNames;
  