// utils/airlineNames.js
const iataToCity = {
    SCL: 'Santiago de Chile - Arturo Merino Benítez',
  ANF: 'Antofagasta - Andrés Sabella',
  ARI: 'Arica - Chacalluta',
  CJC: 'Calama - El Loa',
  CCP: 'Concepción - Carriel Sur',
  IQQ: 'Iquique - Diego Aracena',
  LSC: 'La Serena - La Florida',
  PMC: 'Puerto Montt - El Tepual',
  PUQ: 'Punta Arenas - Presidente Carlos Ibáñez del Campo',
  ZAL: 'Valdivia - Pichoy',
  ZCO: 'Temuco - La Araucanía',
  CPO: 'Copiapó - Desierto de Atacama',
  LSQ: 'Los Ángeles - María Dolores',
  ESR: 'El Salvador - Ricardo García Posada',
  WPR: 'Porvenir - Capitán Fuentes Martínez',
  GXQ: 'Coyhaique - Teniente Vidal',
  BBA: 'Balmaceda - Balmaceda',
  ZOS: 'Osorno - Cañal Bajo Carlos Hott Siebert',
  MHC: 'Castro - Mocopulli',
  VAP: 'Valparaíso - Torquemada',
  LIM: 'Lima - Jorge Chávez',
  CUZ: 'Cusco - Alejandro Velasco Astete',
  AQP: 'Arequipa - Rodríguez Ballón',
  TRU: 'Trujillo - Capitán FAP Carlos Martínez de Pinillos',
  IQT: 'Iquitos - Coronel FAP Francisco Secada Vignetta',
  JUL: 'Juliaca - Inca Manco Cápac',
  PIU: 'Piura - Capitán FAP Guillermo Concha Iberico',
  CIX: 'Chiclayo - Capitán FAP José A. Quiñones Gonzales',
  TPP: 'Tarapoto - Cadete FAP Guillermo del Castillo Paredes',
  TBP: 'Tumbes - Capitán FAP Pedro Canga Rodríguez',
  PCL: 'Pucallpa - Capitán FAP David Abensur Rengifo',
  TCQ: 'Tacna - Coronel FAP Carlos Ciriani Santa Rosa',
  TYL: 'Talara - Capitán FAP Víctor Montes Arias',
  CHM: 'Chimbote - Teniente FAP Jaime Montreuil Morales',
  HUU: 'Huanuco - Alférez FAP David Figueroa Fernandini',
  MGC: 'Moyobamba - Juan Simons Vela',
  SMG: 'Saposoa - San Martin',
  AYP: 'Ayacucho - Coronel FAP Alfredo Mendivil Duarte',
  ANS: 'Andahuaylas - Andahuaylas',
  ATA: 'Anta - Comandante FAP Germán Arias Graziani',
  JAU: 'Jauja - Francisco Carlé',
  YMS: 'Yurimaguas - Moisés Benzaquen Rengifo',
  MEX: 'Ciudad de México - Benito Juárez',
  CUN: 'Cancún',
  GDL: 'Guadalajara - Miguel Hidalgo y Costilla',
  MTY: 'Monterrey - General Mariano Escobedo',
  TIJ: 'Tijuana - General Abelardo L. Rodríguez',
  PVR: 'Puerto Vallarta - Licenciado Gustavo Díaz Ordaz',
  SJD: 'San José del Cabo - Los Cabos',
  BJX: 'León/Guanajuato - Del Bajío',
  QRO: 'Querétaro - Intercontinental',
  MID: 'Merida - Manuel Crescencio Rejón',
  CZM: 'Cozumel',
  HMO: 'Hermosillo - General Ignacio Pesqueira García',
  CUL: 'Culiacán - Bachigualato',
  SLP: 'San Luis Potosí - Ponciano Arriaga',
  VSA: 'Villahermosa - Carlos Rovirosa Pérez',
  CUU: 'Chihuahua - General Roberto Fierro Villalobos',
  MXL: 'Mexicali - General Rodolfo Sánchez Taboada',
  OAX: 'Oaxaca - Xoxocotlán',
  VER: 'Veracruz - General Heriberto Jara',
  TAM: 'Tampico - General Francisco Javier Mina',
  REX: 'Reynosa - General Lucio Blanco',
  TLC: 'Toluca - Licenciado Adolfo López Mateos',
  ZIH: 'Ixtapa/Zihuatanejo',
  LAP: 'La Paz - Manuel Márquez de León',
  ZCL: 'Zacatecas - General Leobardo C. Ruiz',
  AGU: 'Aguascalientes - Licenciado Jesús Terán Peredo',
  TRC: 'Torreón - Francisco Sarabia',
  MTT: 'Minatitlán - Coatzacoalcos',
  PAZ: 'Poza Rica - El Tajín',
  LMM: 'Los Mochis - Valle del Fuerte',
  ZLO: 'Manzanillo - Playa de Oro',
  UPN: 'Uruapan - General Ignacio López Rayón',
  TPQ: 'Tepic - Amado Nervo',
  TAP: 'Tapachula - International',
  MAM: 'Matamoros - General Servando Canales',
  ATL: 'Atlanta - Hartsfield-Jackson',
  LAX: 'Los Ángeles - Los Angeles International',
  ORD: 'Chicago - OHare International',
  DFW: 'Dallas/Fort Worth - Dallas/Fort Worth International',
  DEN: 'Denver - Denver International',
  JFK: 'Nueva York - John F. Kennedy International',
  SFO: 'San Francisco - San Francisco International',
  LAS: 'Las Vegas - McCarran International',
  SEA: 'Seattle - Seattle-Tacoma International',
  MIA: 'Miami - Miami International',
  PHX: 'Phoenix - Phoenix Sky Harbor International',
  IAH: 'Houston - George Bush Intercontinental',
  MCO: 'Orlando - Orlando International',
  EWR: 'Nueva York - Newark Liberty International',
  CLT: 'Charlotte - Charlotte Douglas International',
  MSP: 'Minneapolis - Minneapolis-Saint Paul International',
  DTW: 'Detroit - Detroit Metropolitan Wayne County',
  PHL: 'Filadelfia - Philadelphia International',
  BOS: 'Boston - Logan International',
  LGA: 'Nueva York - LaGuardia',
  BWI: 'Baltimore - Baltimore/Washington International Thurgood Marshall',
  SLC: 'Salt Lake City - Salt Lake City International',
  IAD: 'Washington D.C. - Washington Dulles International',
  SAN: 'San Diego - San Diego International',
  TPA: 'Tampa - Tampa International',
  PDX: 'Portland - Portland International',
  HNL: 'Honolulu - Daniel K. Inouye International',
  DAL: 'Dallas - Dallas Love Field',
  MDW: 'Chicago - Midway International',
  DCA: 'Washington D.C. - Ronald Reagan Washington National',
  STL: 'St. Louis - St. Louis Lambert International',
  RDU: 'Raleigh/Durham - Raleigh-Durham International',
  HOU: 'Houston - William P. Hobby',
  BNA: 'Nashville - Nashville International',
  AUS: 'Austin - Austin-Bergstrom International',
  MCI: 'Kansas City - Kansas City International',
  CLE: 'Cleveland - Cleveland Hopkins International',
  SMF: 'Sacramento - Sacramento International',
  SAT: 'San Antonio - San Antonio International',
  PIT: 'Pittsburgh - Pittsburgh International',
  SJC: 'San José - Norman Y. Mineta San Jose International',
  CVG: 'Cincinnati - Cincinnati/Northern Kentucky International',
  IND: 'Indianápolis - Indianapolis International',
  MKE: 'Milwaukee - General Mitchell International',
  SNA: 'Santa Ana - John Wayne',
  JAX: 'Jacksonville - Jacksonville International',
  OGG: 'Kahului - Kahului',
  ABQ: 'Albuquerque - Albuquerque International Sunport',
  OMA: 'Omaha - Eppley Airfield',
  ANC: 'Anchorage - Ted Stevens Anchorage International',
  RNO: 'Reno - Reno-Tahoe International',
  BUF: 'Búfalo - Buffalo Niagara International',
  ONT: 'Ontario - Ontario International',
  LIH: 'Lihue - Lihue',
  RIC: 'Richmond - Richmond International',
  CHS: 'Charleston - Charleston International',
  BOI: 'Boise - Boise Air Terminal',
  GEG: 'Spokane - Spokane International',
  BUE: 'Buenos Aires',
  GRU: 'Sao Paulo - Guarulhos',
  GIG: 'Rio de Janeiro - Galeão',
  CGH: 'Sao Paulo - Congonhas',
  SDU: 'Río de Janeiro - Santos Dumont',
  BSB: 'Brasilia',
  CNF: 'Belo Horizonte - Confins',
  POA: 'Porto Alegre - Salgado Filho',
  SSA: 'Salvador - Deputado Luís Eduardo Magalhães',
  CWB: 'Curitiba - Afonso Pena',
  REC: 'Recife - Guararapes',
  FOR: 'Fortaleza - Pinto Martins',
  VCP: 'Campinas - Viracopos',
  BEL: 'Belem - Val de Cans',
  MAO: 'Manaus - Eduardo Gomes',
  NAT: 'Natal - Governador Aluízio Alves',
  CGB: 'Cuiabá - Marechal Rondon',
  MCZ: 'Maceió - Zumbi dos Palmares',
  VIX: 'Vitória - Eurico de Aguiar Salles',
  GYN: 'Goiânia - Santa Genoveva',
  SLZ: 'Sao Luís - Marechal Cunha Machado',
  JOI: 'Joinville - Lauro Carneiro de Loyola',
  NVT: 'Navegantes - Ministro Victor Konder',
  FLN: 'Florianópolis - Hercílio Luz',
  IGU: 'Foz do Iguaçu - Cataratas',
  AJU: 'Aracaju - Santa Maria',
  THE: 'Teresina - Senador Petrônio Portella',
  BPS: 'Porto Seguro',
  PVH: 'Porto Velho - Governador Jorge Teixeira de Oliveira',
  RBR: 'Rio Branco - Plácido de Castro',
  TFF: 'Tefé',
  JDO: 'Juazeiro do Norte - Orlando Bezerra de Menezes',
  STM: 'Santarém - Maestro Wilson Fonseca',
  CPV: 'Campina Grande - Presidente João Suassuna',
  CZS: 'Cruzeiro do Sul',
  ATM: 'Altamira',
  PPB: 'Presidente Prudente - Adhemar de Barros',
  MII: 'Marília - Frank Miloye Milenkowichi',
  CAW: 'Campos dos Goytacazes - Bartolomeu Lysandro',
  IZA: 'Juiz de Fora - Zona da Mata',
  UDI: 'Uberlândia - Tenente Coronel Aviador César Bombonato',
  UBA: 'Uberaba - Mário de Almeida Franco',

  // Colombia
  BOG: 'Bogotá - El Dorado',
  MDE: 'Medellín - José María Córdova',
  CLO: 'Cali - Alfonso Bonilla Aragón',
  CTG: 'Cartagena - Rafael Núñez',
  BAQ: 'Barranquilla - Ernesto Cortissoz',
  SMR: 'Santa Marta - Simón Bolívar',
  ADZ: 'San Andrés - Gustavo Rojas Pinilla',
  PEI: 'Pereira - Matecaña',
  AXM: 'Armenia - El Edén',
  BGA: 'Bucaramanga - Palonegro',
  CUC: 'Cucuta - Camilo Daza',
  LET: 'Leticia - Alfredo Vásquez Cobo',
  MZL: 'Manizales - La Nubia',
  EOH: 'Medellín - Olaya Herrera',
  NVA: 'Neiva - Benito Salas',
  PPN: 'Popayán - Guillermo León Valencia',
  PSO: 'Pasto - Antonio Nariño',
  RCH: 'Riohacha - Almirante Padilla',
  TME: 'Tame - Gabriel Vargas Santos',
  VUP: 'Valledupar - Alfonso López Pumarejo',
  VVC: 'Villavicencio - Vanguardia',
  CIM: 'Cimitarra - Cimitarra',
  BUN: 'Buenaventura - Gerardo Tobar López',
  TCO: 'Tumaco - La Florida',
  MCJ: 'Maicao - Jorge Isaacs',
  LPD: 'La Pedrera - La Pedrera',
  PDA: 'Puerto Inírida - Obando',
  MVP: 'Mitú - Fabio Alberto León Bentley',
  EJA: 'Barrancabermeja - Yariguíes',
  CVE: 'Covenas - Covenas',
  GPI: 'Guapi - Juan Casiano',

  // Argentina
  EZE: 'Buenos Aires - Ministro Pistarini (Ezeiza)',
  AEP: 'Buenos Aires - Aeroparque Jorge Newbery',
  COR: 'Cordoba - Ingeniero Ambrosio Taravella',
  MDZ: 'Mendoza - El Plumerillo',
  ROS: 'Rosario - Islas Malvinas',
  BRC: 'San Carlos de Bariloche - Teniente Luis Candelaria',
  NQN: 'Neuquén - Presidente Perón',
  SLA: 'Salta - Martín Miguel de Güemes',
  TUC: 'San Miguel de Tucumán - Teniente General Benjamín Matienzo',
  IGR: 'Puerto Iguazú - Cataratas del Iguazú',
  USH: 'Ushuaia - Malvinas Argentinas',
  REL: 'Trelew - Almirante Marco Andrés Zar',
  RGL: 'Rio Gallegos - Piloto Civil Norberto Fernández',
  FTE: 'El Calafate - Comandante Armando Tola',
  JUJ: 'San Salvador de Jujuy - Gobernador Horacio Guzmán',
  AFA: 'San Rafael - Suboficial Ayudante Santiago Germano',
  CRD: 'Comodoro Rivadavia - General Enrique Mosconi',
  VDM: 'Viedma - Gobernador Edgardo Castello',
  RHD: 'Termas de Río Hondo',
  BHI: 'Bahía Blanca - Comandante Espora',
  PMY: 'Puerto Madryn - El Tehuelche',
  RSA: 'Santa Rosa - Santa Rosa',
  LGS: 'Malargüe - Comodoro D. Ricardo Salomón',
  CPC: 'San Martín de los Andes - Aviador Carlos Campos',
  VLG: 'Villa Gesell - Villa Gesell',
  EHL: 'El Bolsón - El Bolsón',
  RCU: 'Rio Cuarto - Las Higueras',
  PSS: 'Posadas - Libertador General José de San Martín',
  CNQ: 'Corrientes - Doctor Fernando Piragine Niveyro',
  RES: 'Resistencia - Resistencia',
  FMA: 'Formosa - El Pucú',
  CLX: 'Clorinda',
  OYA: 'Goya',
  LLS: 'Las Lomitas',
  SDE: 'Santiago del Estero - Vicecomodoro Ángel de la Paz Aragonés',
  IRJ: 'La Rioja - Capitán Vicente Almandos Almonacid',
  CTC: 'Catamarca - Coronel Felipe Varela',
  VDR: 'Villa Dolores',
  LUQ: 'San Luis - Brigadier Mayor César Raúl Ojeda',
  CNQ: 'Corrientes - Dr. Fernando Piragine Niveyro',
  RGA: 'Rio Grande - Hermes Quijada',
  LHR: 'Londres - Heathrow',
  FRA: 'Frankfurt - Frankfurt am Main',
  AMS: 'Amsterdam - Schiphol',
  MAD: 'Madrid - Adolfo Suárez Madrid-Barajas',
  BCN: 'Barcelona - El Prat',
  MUC: 'Múnich - Franz Josef Strauß',
  FCO: 'Roma - Leonardo da Vinci-Fiumicino',
  LGW: 'Londres - Gatwick',
  ZRH: 'Zúrich - Zúrich',
  CPH: 'Copenhague - Kastrup',
  OSL: 'Oslo - Gardermoen',
  ARN: 'Estocolmo - Arlanda',
  HEL: 'Helsinki - Vantaa',
  DUB: 'Dublín - Dublín',
  BRU: 'Bruselas - Bruselas',
  VIE: 'Viena - Schwechat',
  PRG: 'Praga - Václav Havel',
  WAW: 'Varsovia - Frederic Chopin',
  BUD: 'Budapest - Ferenc Liszt',
  ATH: 'Atenas - Eleftherios Venizelos',
  LIS: 'Lisboa - Humberto Delgado',
  MAN: 'Mánchester - Mánchester',
  DUS: 'Düsseldorf - Düsseldorf',
  HAM: 'Hamburgo - Helmut Schmidt',
  BER: 'Berlín - Brandenburg',
  GVA: 'Ginebra - Ginebra',
  MXP: 'Milán - Malpensa',
  LIN: 'Milán - Linate',
  VCE: 'Venecia - Marco Polo',
  NAP: 'Nápoles - Capodichino',
  PMI: 'Palma de Mallorca - Palma de Mallorca',
  NCE: 'Niza - Costa Azul',
  LYS: 'Lyon - Saint Exupéry',
  TLL: 'Tallin - Lennart Meri',
  RIX: 'Riga - Riga',
  VNO: 'Vilna - Vilnius',
  LED: 'San Petersburgo - Pulkovo',
  SVO: 'Moscú - Sheremetyevo',
  DME: 'Moscú - Domodedovo',
  IST: 'Estambul - Istanbul',
  SAW: 'Estambul - Sabiha Gökçen',
  OTP: 'Bucarest - Henri Coandă',
  SOF: 'Sofía - Sofía',
  BEG: 'Belgrado - Nikola Tesla',
  ZAG: 'Zagreb - Franjo Tuđman',
  DBV: 'Dubrovnik - Dubrovnik',
  SPU: 'Split - Split',
  LCA: 'Larnaca - Larnaca',
  MLA: 'La Valeta - Malta',
  SKG: 'Salónica - Macedonia',
  BFS: 'Belfast - Belfast International',
  EMA: 'East Midlands - East Midlands',
  LTN: 'Londres - Luton',
  STN: 'Londres - Stansted',
  EDI: 'Edimburgo - Edinburgh',
  GLA: 'Glasgow - Glasgow International',
  ABZ: 'Aberdeen - Aberdeen International',
  BHX: 'Birmingham - Birmingham',
  NCL: 'Newcastle - Newcastle International',
  LBA: 'Leeds/Bradford - Leeds Bradford',
  BHD: 'Belfast - George Best Belfast City',
  SEN: 'Southend - London Southend',
  PEK: 'Beijing - Capital International',
  PVG: 'Shanghai - Pudong International',
  HND: 'Tokyo - Haneda',
  NRT: 'Tokyo - Narita',
  ICN: 'Seoul - Incheon International',
  HKG: 'Hong Kong - Hong Kong International',
  SIN: 'Singapore - Changi',
  BKK: 'Bangkok - Suvarnabhumi',
  DEL: 'Delhi - Indira Gandhi International',
  BOM: 'Mumbai - Chhatrapati Shivaji Maharaj International',
  KUL: 'Kuala Lumpur - Kuala Lumpur International',
  MNL: 'Manila - Ninoy Aquino International',
  CGK: 'Jakarta - Soekarno-Hatta International',
  CAN: 'Guangzhou - Baiyun International',
  SZX: 'Shenzhen - Bao\'an International',
  CTU: 'Chengdu - Shuangliu International',
  KIX: 'Osaka - Kansai International',
  FUK: 'Fukuoka - Fukuoka',
  KHH: 'Kaohsiung - Kaohsiung International',
  TPE: 'Taipei - Taoyuan International',
  DPS: 'Denpasar - Ngurah Rai International',
  SGN: 'Ho Chi Minh City - Tan Son Nhat International',
  HAN: 'Hanoi - Noi Bai International',
  CEB: 'Cebu - Mactan-Cebu International',
  KTM: 'Kathmandu - Tribhuvan International',
  PNH: 'Phnom Penh - Phnom Penh International',
  VTE: 'Vientiane - Wattay International',
  RGN: 'Yangon - Yangon International',
  ULN: 'Ulaanbaatar - Chinggis Khaan International',
  TAS: 'Tashkent - Islam Karimov Tashkent International',
  ALA: 'Almaty - Almaty International',
  NQZ: 'Nur-Sultan - Nursultan Nazarbayev International',
  KHI: 'Karachi - Jinnah International',
  LHE: 'Lahore - Allama Iqbal International',
  ISB: 'Islamabad - Islamabad International',
  IKA: 'Tehran - Imam Khomeini International',
  THR: 'Tehran - Mehrabad International',
  TLV: 'Tel Aviv - Ben Gurion',
  RUH: 'Riyadh - King Khalid International',
  JED: 'Jeddah - King Abdulaziz International',
  DMM: 'Dammam - King Fahd International',
  DOH: 'Doha - Hamad International',
  AUH: 'Abu Dhabi - Abu Dhabi International',
  DXB: 'Dubai - Dubai International',
  SHJ: 'Sharjah - Sharjah International',
  BAH: 'Bahrain - Bahrain International',
  MCT: 'Muscat - Muscat International',
  KWI: 'Kuwait City - Kuwait International',
  MLE: 'Malé - Velana International',
  CMB: 'Colombo - Bandaranaike International',
  PTY: 'Panamá - Tocumen International',
  SJO: 'San José - Juan Santamaría International',
  LIR: 'Liberia - Daniel Oduber Quirós International',
  SAL: 'San Salvador - El Salvador International',
  TGU: 'Tegucigalpa - Toncontín International',
  SAP: 'San Pedro Sula - Ramón Villeda Morales International',
  RTB: 'Roatán - Juan Manuel Gálvez International',
  BZE: 'Belice City - Philip S. W. Goldson International',
  MGA: 'Managua - Augusto C. Sandino International',
  GUA: 'Ciudad de Guatemala - La Aurora International',
  CZL: 'Cozumel - Cozumel International',
  HAV: 'La Habana - José Martí International',
  SNU: 'Santa Clara - Abel Santamaría International',
  VRA: 'Varadero - Juan Gualberto Gómez International',
  GCM: 'Gran Caimán - Owen Roberts International',
  KIN: 'Kingston - Norman Manley International',
  MBJ: 'Montego Bay - Sangster International',
  NAS: 'Nassau - Lynden Pindling International',
  PLS: 'Providenciales - Providenciales International',
  SXM: 'Sint Maarten - Princess Juliana International',
  AUA: 'Aruba - Queen Beatrix International',
  CUR: 'Curazao - Hato International',
  BON: 'Bonaire - Flamingo International',
  POS: 'Puerto España - Piarco International',
  TAB: 'Tobago - A.N.R. Robinson International',
  SJU: 'San Juan - Luis Muñoz Marín International',
  STT: 'Saint Thomas - Cyril E. King',
  STX: 'Saint Croix - Henry E. Rohlsen',
  SDQ: 'Santo Domingo - Las Américas International',
  PUJ: 'Punta Cana - Punta Cana International',
  POP: 'Puerto Plata - Gregorio Luperón International',
  FDF: 'Fort-de-France - Martinique Aimé Césaire International',
  PTP: 'Pointe-à-Pitre - Pointe-à-Pitre International',
  BDA: 'Bermuda - L.F. Wade International',
  ANU: 'Antigua - V.C. Bird International',
  GND: 'Granada - Maurice Bishop International',
  SLU: 'Santa Lucía - George F. L. Charles',
  UVF: 'Santa Lucía - Hewanorra International',
  EIS: 'Tortola - Terrance B. Lettsome International',
  SKB: 'Saint Kitts - Robert L. Bradshaw International',
  CCS: 'Caracas - Simón Bolívar International',
  MAR: 'Maracaibo - La Chinita International',
  VLN: 'Valencia - Arturo Michelena International',
  PMV: 'Porlamar - Santiago Mariño Caribbean International',
  BLA: 'Barcelona - General José Antonio Anzoátegui International',
  PZO: 'Puerto Ordaz - Manuel Carlos Piar Guayana',
  LFR: 'La Fría - La Fría',
  LSP: 'Las Piedras - Josefa Camejo International',
  CBL: 'Ciudad Bolívar - Tomás de Heres',
  CUM: 'Cumaná - Antonio José de Sucre',
  CZE: 'Coro - José Leonardo Chirino',
  ELX: 'El Tigre - El Tigre',
  EOR: 'El Dorado - El Dorado',
  GUI: 'Guiria - Guiria',
  LAG: 'La Guaira - La Guaira',
  MUN: 'Maturín - José Tadeo Monagas International',
  PYH: 'Puerto Ayacucho - Cacique Aramare',
  SCI: 'San Cristóbal - Paramillo',
  SFD: 'San Fernando de Apure - Las Flecheras',
  SOM: 'San Tomé - San Tomé',
  STD: 'Santo Domingo - Mayor Buenaventura Vivas',
  SNV: 'Santa Elena de Uairén - Santa Elena de Uairén',
  TUV: 'Tucupita - Tucupita',
  VIG: 'El Vigía - Juan Pablo Pérez Alfonzo',
  UIO: 'Quito - Mariscal Sucre International',
  GYE: 'Guayaquil - José Joaquín de Olmedo International',
  CUE: 'Cuenca - Mariscal La Mar',
  GPS: 'Galápagos (Baltra) - Seymour',
  SCY: 'Galápagos (San Cristóbal) - San Cristóbal',
  MEC: 'Manta - Eloy Alfaro International',
  LTX: 'Latacunga - Cotopaxi International',
  ESM: 'Esmeraldas - General Rivadeneira',
  XMS: 'Macas - Coronel Edmundo Carvajal',
  MCH: 'Machala - General Manuel Serrano',
  PTZ: 'Pastaza - Rio Amazonas',
  TPC: 'Tarapoa - Tarapoa',
  LGQ: 'Nueva Loja (Lago Agrio) - Lago Agrio',
  TPN: 'Tiputini - Tiputini',
  LOH: 'Loja - Ciudad de Catamayo',
  PVO: 'Portoviejo - Reales Tamarindos',
  TSC: 'Taisha - Taisha',
  PYO: 'Putumayo - Putumayo',
  MVD: 'Montevideo - Carrasco International',
  PDP: 'Punta del Este - Capitán Corbeta CA Curbelo International',
  STY: 'Salto - Nueva Hespérides International',
  MLZ: 'Melo - Cerro Largo',
  ATI: 'Artigas - Artigas International',
  CYR: 'Colonia del Sacramento - Laguna de los Patos International',
  DZO: 'Durazno - Santa Bernardina International',
  PDU: 'Paysandú - Tydeo Larre Borges',
  RVY: 'Rivera - Rivera International',
  TAW: 'Tacuarembó - Tacuarembó',
  TYT: 'Treinta y Tres - Treinta y Tres',
  ASU: 'Asunción - Silvio Pettirossi International',
  AGT: 'Ciudad del Este - Guaraní International',
  PJC: 'Pedro Juan Caballero - Dr. Augusto Roberto Fuster International',
  CIO: 'Concepción - Teniente Colina',
  ESG: 'Mariscal Estigarribia - Dr. Luis María Argaña International',
  PIL: 'Pilar - Carlos Miguel Jiménez',
  AXM: 'Filadelfia - Filadelfia',
  VMI: 'Vallemí - Vallemí',
  FLM: 'Filadelfia - Filadelfia',
  VVI: 'Santa Cruz - Viru Viru International',
  LPB: 'La Paz - El Alto International',
  CBB: 'Cochabamba - Jorge Wilstermann International',
  TJA: 'Tarija - Capitán Oriel Lea Plaza',
  TDD: 'Trinidad - Teniente Jorge Henrich Arauz',
  RIB: 'Riberalta - Capitán Av. Selin Zeitun Lopez',
  PSZ: 'Puerto Suárez - Capitán Av. Salvador Ogaya G.',
  SRZ: 'Santa Cruz - El Trompillo',
  UYU: 'Uyuni - Joya Andina',
  RBQ: 'Rurrenabaque - Rurrenabaque',
  SRE: 'Sucre - Alcantari International',
  BYC: 'Yacuiba - Yacuiba',
  CIJ: 'Cobija - Capitán Aníbal Arab Fadul',
  GYA: 'Guayaramerín - Guayaramerín',
  REY: 'Riberalta - Reyes',
  CDG: 'Paris - Charles de Gaulle',
  ORY: 'Paris - Orly',
  BVA: 'Beauvais - Beauvais-Tillé',
  MRS: 'Marsella - Provence',
  NCE: 'Niza - Côte d\'Azur',
  LYS: 'Lyon - Saint-Exupéry',
  TLS: 'Toulouse - Blagnac',
  BOD: 'Burdeos - Mérignac',
  SXB: 'Estrasburgo - Entzheim',
  LIL: 'Lille - Lesquin',
  NTE: 'Nantes - Atlantique',
  MPL: 'Montpellier - Méditerranée',
  BIA: 'Bastia - Poretta',
  AJA: 'Ajaccio - Napoleón Bonaparte',
  FNI: 'Nîmes - Garons',
  RNS: 'Rennes - Saint-Jacques',
  CFR: 'Caen - Carpiquet',
  BIQ: 'Biarritz - Pays Basque',
  UIP: 'Quimper - Pluguffan',
  LRH: 'La Rochelle - Île de Ré',
  LRT: 'Lorient - Lann Bihoué',
  BES: 'Brest - Bretagne',
  PGF: 'Perpiñán - Rivesaltes',
  PIS: 'Poitiers - Biard',
  LDE: 'Lourdes - Tarbes-Pyrénées',
  PUF: 'Pau - Pyrénées',
  XCR: 'Châlons-en-Champagne - Vatry',
  DOL: 'Deauville - Saint-Gatien',
  MLH: 'Mulhouse - EuroAirport Basel-Mulhouse-Freiburg',
  CCF: 'Carcasona - Salvaza',
  TLN: 'Toulon - Hyères',
  LIG: 'Limoges - Bellegarde',
  ANG: 'Angers - Loire',
  ETZ: 'Metz-Nancy - Lorraine',
  TUF: 'Tours - Val de Loire',
  CFE: 'Clermont-Ferrand - Auvergne',
  RAY: 'Bastia - Calvi Sainte-Catherine',
  DNR: 'Dinard - Pleurtuit-Saint-Malo'

    // Agrega más destinos según sea necesario
  };
  
  export default iataToCity;
  